#!/usr/bin/env python3
"""
Historical Results Tracker
Appends current run statistics to a rolling history log for trend analysis.
Usage:
    python automation/utils/history_tracker.py \
        --input automation/reports \
        --run-id 12345 \
        --run-number 42 \
        --branch main \
        --timestamp 2026-08-05T12:00:00Z
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


def load_results(reports_dir: str) -> list:
    results = []
    base = Path(reports_dir)
    for f in base.rglob('*.json'):
        if 'history' in str(f):
            continue
        try:
            with open(f, encoding='utf-8') as fh:
                data = json.load(fh)
            if isinstance(data, list):
                results.extend(data)
            elif isinstance(data, dict) and 'tests' in data:
                results.extend(data['tests'])
        except Exception:
            pass
    return results


def compute_run_stats(results: list) -> dict:
    total = len(results)
    passed = sum(1 for r in results if r.get('status', '').lower() in ('passed', 'pass'))
    failed = sum(1 for r in results if r.get('status', '').lower() in ('failed', 'fail', 'error'))
    skipped = sum(1 for r in results if r.get('status', '').lower() in ('skipped', 'skip'))
    rate = round(passed / total * 100, 2) if total > 0 else 0.0
    return {'total': total, 'passed': passed, 'failed': failed, 'skipped': skipped, 'rate': rate}


def record_history(
    reports_dir: str,
    run_id: str,
    run_number: str,
    branch: str,
    timestamp: str,
):
    results = load_results(reports_dir)
    stats = compute_run_stats(results)

    history_entry = {
        'run_id': run_id,
        'run_number': int(run_number) if run_number.isdigit() else run_number,
        'branch': branch,
        'timestamp': timestamp or datetime.utcnow().isoformat(),
        'base_url': os.getenv('BASE_URL', ''),
        **stats,
    }

    history_dir = os.path.join(reports_dir, 'history')
    os.makedirs(history_dir, exist_ok=True)

    # Append to rolling history file
    history_file = os.path.join(history_dir, 'runs.json')
    history = []
    if os.path.exists(history_file):
        try:
            with open(history_file, encoding='utf-8') as f:
                history = json.load(f)
        except Exception:
            history = []

    history.append(history_entry)
    # Keep last 100 runs
    history = history[-100:]

    with open(history_file, 'w', encoding='utf-8') as f:
        json.dump(history, f, indent=2)
    print(f"History updated: {history_file} ({len(history)} runs)")

    # Write individual run snapshot
    run_file = os.path.join(history_dir, f'run_{run_number or run_id}.json')
    with open(run_file, 'w', encoding='utf-8') as f:
        json.dump(history_entry, f, indent=2)

    # Generate trend markdown
    _write_trend_md(history, history_dir)
    return history_entry


def _write_trend_md(history: list, output_dir: str):
    """Write a simple trend markdown table."""
    rows = ''
    for h in history[-20:]:  # Last 20 runs
        status = '✅' if h.get('rate', 0) >= 95 else '❌'
        rows += (f"| #{h.get('run_number', '?')} | {h.get('branch', '')} | "
                 f"{h.get('total', 0)} | {h.get('passed', 0)} | {h.get('failed', 0)} | "
                 f"{h.get('rate', 0)}% | {status} | {h.get('timestamp', '')[:19]} |\n")

    md = f"""# FlowTime — Test Execution History

Last {len(history[-20:])} runs:

| Run | Branch | Total | ✅ Pass | ❌ Fail | Rate | Status | Timestamp |
|-----|--------|-------|---------|---------|------|--------|-----------|
{rows}
*Auto-generated by history_tracker.py*
"""
    trend_path = os.path.join(output_dir, 'trend.md')
    with open(trend_path, 'w', encoding='utf-8') as f:
        f.write(md)
    print(f"Trend report: {trend_path}")


def main():
    parser = argparse.ArgumentParser(description='Historical Results Tracker')
    parser.add_argument('--input', default='automation/reports')
    parser.add_argument('--run-id', default='local')
    parser.add_argument('--run-number', default='0')
    parser.add_argument('--branch', default='main')
    parser.add_argument('--timestamp', default='')
    args = parser.parse_args()

    entry = record_history(
        reports_dir=args.input,
        run_id=args.run_id,
        run_number=args.run_number,
        branch=args.branch,
        timestamp=args.timestamp,
    )
    print(f"Run recorded: {entry}")


if __name__ == '__main__':
    main()
